### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'

### ISSUE THREAD

**Issue by Abhijithm2447** [anykate/demo#1]
(python36) C:\Users\abhijith.m\0 zerone\Django\demo-master>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 587, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 572, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 290, in run
    self.run_loop()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 296, in run_loop
    next(ticker)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 336, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 352, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 251, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 103, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\site-packages\django\utils\autoreload.py", line 138, in iter_modules_and_files
    if not path.exists():
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\pathlib.py", line 1336, in exists
    self.stat()
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "C:\Users\abhijith.m\AppData\Local\conda\conda\envs\python36\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'

**Comment by anykate** [comment]
There is no issue with the code in the github repo - check the error - It clearly states there is some Windows issue which is specific to your version of Windows. It works fine on my Windows 10 Pro and Ubuntu 18.04 VM.
